### ISSUE TITLE
Please include this

### ISSUE THREAD

**Issue by Jamalam360** [Shiny-Octo-Robot/shiny-octo-robot#1]
Please make sure this comment is included: https://github.com/uBlockOrigin/uAssets/discussions/24177#discussioncomment-9821526

You can see that their filter breaks the mod description, and you can also see that before that comment I repeatedly tried to warn them that this was the case.

Also in that thread is them calling us (modders opposed to the change?) a 'moronic team'

**Comment by Jamalam360** [comment]
You can also see these two locked issues:

https://github.com/uBlockOrigin/uAssets/issues/24130
https://github.com/uBlockOrigin/uAssets/issues/24171

with an incredible amount of comments marked as spam. I haven't read all of them, but from the ones I read it seemed like modders were just trying to make people aware of how much they depend on these ads.

although, do note that it is within ublocks policies to block these ads. personally my issue is that they are being rude to people discussing the changes and that they are breaking non-ad content.

**Comment by CassieRoseZA** [comment]
Hi will do
