### ISSUE TITLE
thingys

### ISSUE THREAD

**Issue by omo50** [Shiny-Octo-Robot/shiny-octo-robot#2]
![image](https://github.com/CassieRoseZA/shiny-octo-robot/assets/144749186/005dc66a-88d0-4aaf-ac9b-cf8b4e833b4a)
![image](https://github.com/CassieRoseZA/shiny-octo-robot/assets/144749186/7bd4997c-2263-4f82-b05f-67b6fe6864ea)
![image](https://github.com/CassieRoseZA/shiny-octo-robot/assets/144749186/0fc4cc57-35b0-4c4a-b0c4-286b8ff3af8d)

also please make this repo private, they are likely stalking our pages

**Comment by MundM2007** [comment]
If more stuff is needed, this contains more Images of mostly deleted Messages https://imgur.com/a/sXNS7IS copied from the Reddit post

**Comment by CassieRoseZA** [comment]
> If more stuff is needed, this contains more Images of mostly deleted Messages https://imgur.com/a/sXNS7IS copied from the Reddit post

That's my imgur link i put on the thread lol ill add too it

**Comment by MundM2007** [comment]
> > If more stuff is needed, this contains more Images of mostly deleted Messages https://imgur.com/a/sXNS7IS copied from the Reddit post
> 
> That's my imgur link i put on the thread lol ill add too it

Ah That's funny. i didn't notice

**Comment by CassieRoseZA** [comment]
https://discord.com/invite/MvjEssCA

**Comment by CassieRoseZA** [comment]
Adding somewhere a lil more private as to not monitor
